"use client";
import "./globals.css";
import { Nunito } from "next/font/google";
import { ApolloProvider } from "@apollo/client";
import { SessionProvider } from "next-auth/react";
import HeaderPage from "./header";

import client from "@/lib/apollo";

const nunito = Nunito({ subsets: ["latin"] });

// export const metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={
          nunito.className +
          " overflow-y-scroll scrollbar-thumb-zinc-700 scrollbar-thumb-rounded-2xl scrollbar-track-latte scrollbar-thin"
        }
      >
        <SessionProvider>
          <ApolloProvider client={client}>
            <HeaderPage />
            <main>{children}</main>
          </ApolloProvider>
        </SessionProvider>
      </body>
    </html>
  );
}
